version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/app"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "composer"
    commit-message:
      prefix: "build(composer)"
      include: "scope"
    groups:
      composer-patch:
        update-types:
          - "patch"
