services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
    depends_on:
      - mysql

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"        # publier sur 8000 pour éviter le port 80 de Laragon
    depends_on:
      - php

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
