services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www
    env_file:
      - .env.dist
    entrypoint: ["/var/www/docker/php/entrypoint.sh"]
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - php

  mysql:
    image: mysql:8.4
    env_file:
      - .env.dist
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

    # --- healthcheck pour déclarer « healthy » dès que MySQL accepte les connexions ---
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      retries: 10
      timeout: 3s
      start_period: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file:
      - .env.dist
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db_data:
