services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www
    env_file:
      - .env
    depends_on:
      - mysql

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - php

  mysql:
    image: mysql:8.4
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
