name: 🚀 Feature
description: Proposer ou détailler une nouvelle fonctionnalité
title: "feat: <titre court>"
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        ## Objectif utilisateur
        _Quel problème résout-on ?_
  - type: textarea
    id: user-value
    attributes:
      label: Objectif utilisateur
      placeholder: Ex. « En tant que candidat, je veux ajouter une candidature en 30 s »
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Critères d’acceptation
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: dropdown
    id: estimate
    attributes:
      label: Estimation (story points)
      options:
        - 1
        - 2
        - 3
        - 5
        - 8
        - 13
        - 21
        - 34
  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      options:
        - p0
        - p1
        - p2
