name: Auto-merge Dependabot patch updates

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug update type
        run: echo "update-type=${{ steps.metadata.outputs['update-type'] }}"

      - name: Enable auto-merge (squash) when semver patch
        if: steps.metadata.outputs['update-type'] == 'version-update:semver-patch'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          # 👇 Donne explicitement le numéro de PR
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
          token: ${{ secrets.GITHUB_TOKEN }}

      # (Optionnel) activer aussi pour MINOR
      # - name: Enable auto-merge (squash) when semver minor
      #   if: steps.metadata.outputs['update-type'] == 'version-update:semver-minor'
      #   uses: peter-evans/enable-pull-request-automerge@v3
      #   with:
      #     pull-request-number: ${{ github.event.pull_request.number }}
      #     merge-method: squash
      #     token: ${{ secrets.GITHUB_TOKEN }}
