name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build --pull --progress plain

      # 👉 exécution EN ROOT (pas de --user) : écrit dans /etc/gitconfig
      - name: Mark /var/www as safe for Git
        run: docker compose run --rm --workdir /var/www/app php git config --system --add safe.directory /var/www

      - name: Install dev dependencies
        run: docker compose run --rm --user $(id -u):$(id -g) --workdir /var/www/app php composer install -n --prefer-dist

      - name: Run PHPStan
        run: docker compose run --rm --user $(id -u):$(id -g) --workdir /var/www/app php vendor/bin/phpstan analyse --level max

  test:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build --pull --progress plain

      # 👉 reste en root pour la config Git
      - name: Mark /var/www as safe for Git
        run: docker compose run --rm --workdir /var/www/app php git config --system --add safe.directory /var/www

      - name: Run unit tests
        run: docker compose run --rm --user $(id -u):$(id -g) -e APP_ENV=test --workdir /var/www/app php bin/simple-phpunit --testdox

  build:
    name: Build Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build --pull --progress plain

      # 👉 config Git en root
      - name: Mark /var/www as safe for Git
        run: docker compose run --rm --workdir /var/www/app php git config --system --add safe.directory /var/www

      - name: Install prod dependencies
        run: docker compose run --rm --user $(id -u):$(id -g) --workdir /var/www/app php composer install -n --no-dev --prefer-dist

      - name: Run build script
        run: docker compose run --rm --user $(id -u):$(id -g) --workdir /var/www/app php ./scripts/build.sh
