# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build --pull --progress plain
      - run: |
          docker compose run --rm \
            --user $(id -u):$(id -g) \
            --workdir /var/www/app \
            php composer install -n --prefer-dist --no-scripts
      - run: |
          docker compose run --rm \
            --user $(id -u):$(id -g) \
            --workdir /var/www/app \
            php vendor/bin/phpstan analyse --level max

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build --pull --progress plain
      # 1) Installation des dépendances PHP
      - name: Composer install (no-scripts)
        run: |
          docker compose run --rm \
            --user $(id -u):$(id -g) \
            --workdir /var/www \
            php sh -lc '
              git config --global --add safe.directory /var/www &&
              composer install -n --prefer-dist --no-scripts
            '

    # 2) Exécution de la suite de tests
      - name: PHPUnit
        run: |
          docker compose run --rm \
            --user $(id -u):$(id -g) \
            -e APP_ENV=test \
            --workdir /var/www \
            php vendor/bin/phpunit --testdox

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build --pull --progress plain
      - run: |
          docker compose run --rm \
            --user $(id -u):$(id -g) \
            --workdir /var/www/app \
            php composer install -n --no-dev --prefer-dist --no-scripts
      - run: |
          docker compose run --rm \
            --user $(id -u):$(id -g) \
            --workdir /var/www/app \
            php ./scripts/build.sh
