name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build --pull --progress plain

      - name: Install dev dependencies
        run: docker compose run --rm --workdir /var/www/app php composer install -n --prefer-dist

      - name: Run PHPStan
        run: docker compose run --rm --workdir /var/www/app php vendor/bin/phpstan analyse --level max

  test:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build --pull --progress plain

      - name: Run unit tests
        run: docker compose run --rm -e APP_ENV=test --workdir /var/www/app php bin/simple-phpunit --testdox


  build:
    name: Build Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build --pull --progress plain

      - name: Install prod dependencies
        run: docker compose run --rm --workdir /var/www/app php composer install -n --no-dev --prefer-dist

      - name: Run build script
        run: docker compose run --rm --workdir /var/www/app php ./scripts/build.sh

